### ISSUE TITLE
项目规划 ?

### ISSUE THREAD

**Issue by zeusro** [AliyunContainerService/kubernetes-ops-handbook#1]
纯英文,不需要中文吗?

我最近 fork 了别人的仓库,打算把我之前 `kubernetes` 相关博文归集一下.

https://github.com/zeusro/awesome-kubernetes-notes/blob/master/source/chapter_6.md

如果有中文规划的话,我可以加点内容上去.

**Comment by ringtail** [comment]
> 纯英文,不需要中文吗?
> 
> 我最近 fork 了别人的仓库,打算把我之前 `kubernetes` 相关博文归集一下.
> 
> https://github.com/zeusro/awesome-kubernetes-notes/blob/master/source/chapter_6.md
> 
> 如果有中文规划的话,我可以加点内容上去.

这个项目的目的是配合https://github.com/ringtail/kubectl-pexec，增加内置的场景化脚本仓库。
